version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:12
    working_directory: ~/insurello
    steps:
      - checkout
      - run: make setup
      - run: make lint
      - run: make build
      - run: make test
